### ISSUE TITLE
Consider using queue interprop as abstraction for queues

### ISSUE THREAD

**Issue by makasim** [monsieurbiz/monsieurbiz_amqp#1]
Hello!

Please look at https://github.com/queue-interop/queue-interop project. Using interfaces from it allows us reuse some implementations like enqueue, which supports a lot of transports. You can outsource some code

**Comment by jacquesbh** [comment]
Hi,

Sorry, the purpose of this module is really simple. We don't want to improve and make it become a big application.

Thanks.
